In [1]:
import torch
import time

## 1

In [2]:
A = torch.full((12,12),1)
A

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [3]:
A[1::6,:] = 2
A

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [4]:
A[:,1::6] = 2
A

tensor([[1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1.]])

In [5]:
A[:,10] = 2
A[10,:] = 2
A

tensor([[1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.]])

In [6]:
A[3,3] = 3
A[4,3] = 3
A[4,4] = 3
A[3,4] = 3
A

tensor([[1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [1., 2., 1., 3., 3., 1., 1., 2., 1., 1., 2., 1.],
        [1., 2., 1., 3., 3., 1., 1., 2., 1., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.]])

In [7]:
A[3,8] = 3
A[3,9] = 3
A[4,9] = 3
A[4,8] = 3
A

tensor([[1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [1., 2., 1., 3., 3., 1., 1., 2., 3., 3., 2., 1.],
        [1., 2., 1., 3., 3., 1., 1., 2., 3., 3., 2., 1.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.]])

In [8]:
A[8,3] = 3
A[9,3] = 3
A[9,4] = 3
A[8,4] = 3
A[8,8] = 3
A[9,8] = 3
A[9,9] = 3
A[8,9] = 3
A

tensor([[1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [1., 2., 1., 3., 3., 1., 1., 2., 3., 3., 2., 1.],
        [1., 2., 1., 3., 3., 1., 1., 2., 3., 3., 2., 1.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 3., 3., 1., 1., 2., 3., 3., 2., 1.],
        [1., 2., 1., 3., 3., 1., 1., 2., 3., 3., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1.]])

## 2

In [9]:
B = torch.normal(2,3,size=(5000,5000))
t1 = time.perf_counter()

In [10]:
C = torch.normal(3,2,size=(5000,5000))
t2 = time.perf_counter()

In [11]:
D = torch.mm(B,C)
D

tensor([[29537.6152, 29888.0430, 29237.7520,  ..., 29507.8379, 29197.8848,
         29054.9375],
        [29635.0762, 30075.3047, 29620.4902,  ..., 31067.4551, 29889.2129,
         31028.4434],
        [30035.4023, 30866.2695, 31232.1094,  ..., 31196.3828, 29796.3613,
         30433.6797],
        ...,
        [30434.5176, 29820.7188, 30483.8438,  ..., 30125.8125, 29647.6719,
         29482.8359],
        [29683.5566, 29932.5938, 30109.6621,  ..., 30411.7891, 29491.7695,
         29622.1250],
        [30249.9395, 30500.4434, 30338.2871,  ..., 31695.3770, 30710.2383,
         30938.2461]])

In [12]:
t = t2 - t1
t

9.802463082000031

In [13]:
flops = t / (5000*5000*5000) 
flops

7.841970465600025e-11

## 3

In [15]:
def mul_row(a):
    k = 2
    for i in range(1,len(a)):
        a[i] = a[i] * i+2
    return a


In [16]:
m = torch.full((4,8),2.0)
m

tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.]])

In [17]:
c = mul_row(m)
c

tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
        [4., 4., 4., 4., 4., 4., 4., 4.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [8., 8., 8., 8., 8., 8., 8., 8.]])

In [18]:
def mul_row_fast(n):
    k = 2
    for i in range(len(n)):
        n[1:] = n[1:] * i+2
    return n